# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SciStorm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google/Analytics'

  pod 'Google/SignIn'
  # Pods for SciStorm

  target 'SciStormTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SciStormUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
